version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
naturalist = true
everycomp = true
farmersdelight = true
supplementaries = true
storagedrawers = true
factory_blocks = true
simplemagnets = true
cookingforblockheads = true
bedspreads = true
industrialforegoing = true
croptopia = true
mekanism = true
storagedelight = true
buildinggadgets2 = true
aquaculture = true
quark = true
justdirethings = true
sereneseasons = true
sfm = true
stardew_fishing = true
twigs = true
minecraft = true
pamhc2crops = true
paraglider = true
comforts = true
chalk = true
plushie_buddies = true
farmingforblockheads = true
sophisticatedstorage = true
ae2 = true
mekanismgenerators = true
functionalstorage = true
buzzier_bees = true
waystones = true
pamhc2trees = true
oritech = true
handcrafted = true
chisel = true
charginggadgets = true
snowrealmagic = true
moonlight = true
crittersandcompanions = true
sophisticatedbackpacks = true
exposure = true
